apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: v0.43.1
      {{- with .Values.controller.deployment.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end}}
    pipeline.tekton.dev/release: v0.43.1
    version: v0.43.1
  name: tekton-pipelines-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: tekton-pipelines
  template:
    metadata:
      annotations:
        fake: value
          {{- with .Values.controller.pod.annotations }}
            {{- toYaml . | nindent 8 }}
          {{- end}}
      labels:
        app: tekton-pipelines-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: tekton-pipelines
        app.kubernetes.io/version: v0.43.1
          {{- with .Values.controller.pod.labels }}
            {{- toYaml . | nindent 8 }}
          {{- end}}
        pipeline.tekton.dev/release: v0.43.1
        version: v0.43.1
    spec:
      affinity:
          {{- with .Values.controller.affinity }}
            {{- toYaml . |  nindent 8 }}
          {{- end }}
      containers:
      - args:
        - -kubeconfig-writer-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.43.1@sha256:b635b3cb4f00cf051d7ac9900c0f23b92f2b010107aec3f6e4eaedf1bbb4518c
        - -git-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.43.1@sha256:bac704a7781854bf41fb1ebb4f06d42c82d51262b426473837b6fcea405869e4
        - -entrypoint-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.43.1@sha256:b3ecb6dcfd1f54018e689a67def78a910d5e620e2215e87808b2b4ffb6c3e36e
        - -nop-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.43.1@sha256:022854b3c9db2ca312f44ead3f867a320788bb044f21a4975d2d48ae5fe04069
        - -sidecarlogresults-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.43.1@sha256:f61791afdf90a6ece9126a767e7dcd2a169e57e125a6cf999250e3171210f937
        - -imagedigest-exporter-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.43.1@sha256:e8b6f8db3d7fd5b908718533dd437d093e9abbe39ee207be72cfc49e0348ef40
        - -pr-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.43.1@sha256:e71bb27bee7f9c8789aa128ec3b8d684c45e825905c91cb0dd6988c168e7c654
        - -workingdirinit-image
        - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.43.1@sha256:8e5913a83252d27eda625b30cd4cd1a12138acdb2dbfec514c53d5b02bfd5cb2
        - -gsutil-image
        - gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
        - -shell-image
        - cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
        - -shell-image-win
        - mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_DEFAULTS_NAME
          value: config-defaults
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: CONFIG_ARTIFACT_BUCKET_NAME
          value: config-artifact-bucket
        - name: CONFIG_ARTIFACT_PVC_NAME
          value: config-artifact-pvc
        - name: CONFIG_FEATURE_FLAGS_NAME
          value: feature-flags
        - name: CONFIG_LEADERELECTION_NAME
          value: config-leader-election
        - name: CONFIG_TRUSTED_RESOURCES_NAME
          value: config-trusted-resources
        - name: SSL_CERT_FILE
          value: /etc/config-registry-cert/cert
        - name: SSL_CERT_DIR
          value: /etc/ssl/certs
        - name: METRICS_DOMAIN
          value: tekton.dev/pipeline
        envFrom:
        - secretRef:
            name: '{{ .Values.controller.envFromSecret }}'
            optional: true
        livenessProbe:
          httpGet:
            path: /health
            port: probes
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: tekton-pipelines-controller
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8080
          name: probes
        readinessProbe:
          httpGet:
            path: /readiness
            port: probes
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /etc/config-logging
          name: config-logging
        - mountPath: /etc/config-registry-cert
          name: config-registry-cert
        - mountPath: /etc/verification-secrets
          name: verification-secrets
          readOnly: true
        image: {{ .Values.controller.deployment.image }}
      nodeSelector:
          {{- with .Values.controller.nodeSelector }}
            {{- toYaml . |  nindent 8 }}
          {{- end}}
      serviceAccountName: tekton-pipelines-controller
      tolerations:
          {{- with .Values.controller.tolerations }}
            {{- toYaml . |  nindent 6 }}
          {{- end}}
      volumes:
      - configMap:
          name: config-logging
        name: config-logging
      - configMap:
          name: config-registry-cert
        name: config-registry-cert
      - name: verification-secrets
        secret:
          optional: true
          secretName: verification-secrets