featureFlags:
  # Setting this flag will determine which gated features are enabled.
  # Acceptable values are "stable" or "alpha".
  enable-api-fields: "stable"
  # Setting this field with valid regex pattern matching the pattern will exclude labels from
  # getting added to resources created by the EventListener such as the deployment
  labels-exclusion-pattern: ""
